/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;

/**
 *
 * @author Christian
 */
public class HeaderFooterPageEvent extends PdfPageEventHelper {
    
    String header, email, dateTime;
    int maxPage;
    
    HeaderFooterPageEvent (String header, String email, String dateTime, double maxPage){
        this.header = header;
        this.email = email;
        this.dateTime = dateTime;
        this.maxPage = (int)maxPage;
              
    }
     @Override
    public void onStartPage(PdfWriter writer, Document document) {
        Rectangle rect = writer.getBoxSize("rect");
        ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_LEFT, new Phrase(header), rect.getLeft() + 30, rect.getTop() + 20, 0);
    }

    @Override
    public void onEndPage(PdfWriter writer, Document document) {
        Rectangle rect = writer.getBoxSize("rect");
        ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_LEFT, new Phrase("Page " + writer.getCurrentPageNumber() + " of " + maxPage), rect.getLeft() + 30, rect.getBottom() + 50, 0);
        ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_LEFT, new Phrase("Report Generated by: " + email + " at " + dateTime), rect.getLeft() + 30, rect.getBottom() + 30, 0);
    }
    
}
